import { arraySidebar } from 'vuepress-theme-hope'

export const go = arraySidebar([
    '',
    'mac-go-env',
    'base',
    'go-constant',
    'go-cross-compiler',
    'go-base-datatype',
    'go-string',
    'go-slice',
    'go-map',
    'go-data-convert',
    'go-method',
    'go-interface',
    'go-oop',
    'go-struct-interface',
    'go-struct-memory-layout',
    'go-pointer',
    'go-time',
    'go-file',
    'go-goroutine',
    'go-channel',
    'go-select',
    'go-concurrent-base',
    'go-lock',
    'go并发安全与锁',
    'go-package',
    'go-error',
    'go-module-unit',
    'go-interview',
])
